[2024-05-25T06:28:00.919+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T06:28:00.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_deploy_model.train_model manual__2024-05-25T06:28:00.168887+00:00 [queued]>
[2024-05-25T06:28:00.931+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_deploy_model.train_model manual__2024-05-25T06:28:00.168887+00:00 [queued]>
[2024-05-25T06:28:00.931+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-25T06:28:00.936+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-25 06:28:00.168887+00:00
[2024-05-25T06:28:00.938+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T06:28:00.938+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-05-25T06:28:00.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_and_deploy_model', 'train_model', 'manual__2024-05-25T06:28:00.168887+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/train_and_deploy_dag.py', '--cfg-path', '/tmp/tmp1rgo3oih']
[2024-05-25T06:28:00.939+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask train_model
[2024-05-25T06:28:00.955+0000] {task_command.py:426} INFO - Running <TaskInstance: train_and_deploy_model.train_model manual__2024-05-25T06:28:00.168887+00:00 [running]> on host 2fc9adb3db3b
[2024-05-25T06:28:00.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_deploy_model' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T06:28:00.168887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T06:28:00.168887+00:00'
[2024-05-25T06:28:00.983+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T06:28:03.203+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T06:28:03.203+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/train_and_deploy_dag.py", line 29, in train_model
    raise Exception(f"Training script failed: {result.stderr}")
Exception: Training script failed: Traceback (most recent call last):
  File "/scripts/train_svd.py", line 52, in <module>
    train_model()
  File "/scripts/train_svd.py", line 43, in train_model
    os.makedirs('/metrics')
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/metrics'

[2024-05-25T06:28:03.207+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train_and_deploy_model, task_id=train_model, run_id=manual__2024-05-25T06:28:00.168887+00:00, execution_date=20240525T062800, start_date=20240525T062800, end_date=20240525T062803
[2024-05-25T06:28:03.212+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task train_model (Training script failed: Traceback (most recent call last):
  File "/scripts/train_svd.py", line 52, in <module>
    train_model()
  File "/scripts/train_svd.py", line 43, in train_model
    os.makedirs('/metrics')
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/metrics'
; 76)
[2024-05-25T06:28:03.255+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T06:28:03.266+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-25T06:28:03.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
