[2024-05-24T11:49:49.451+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T11:49:49.461+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2024-05-24T11:49:49.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2024-05-24T11:49:49.470+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-24T11:49:49.480+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_to_s3> on 2023-03-13 00:00:00+00:00
[2024-05-24T11:49:49.483+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T11:49:49.484+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_from_github_to_s3', 'download_and_upload_to_s3', 'scheduled__2023-03-13T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/upload_from_github_to_s3_dag.py', '--cfg-path', '/tmp/tmp5cbjfuvp']
[2024-05-24T11:49:49.485+0000] {standard_task_runner.py:63} INFO - Started process 73 to run task
[2024-05-24T11:49:49.486+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask download_and_upload_to_s3
[2024-05-24T11:49:49.513+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [running]> on host b2ab95bd73fd
[2024-05-24T11:49:49.551+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_from_github_to_s3' AIRFLOW_CTX_TASK_ID='download_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-13T00:00:00+00:00'
[2024-05-24T11:49:49.552+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T11:49:50.036+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-24T11:49:50.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T11:49:50.083+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/upload_from_github_to_s3_dag.py", line 33, in download_and_upload_to_s3
    s3 = boto3.client('s3', endpoint_url='http://fake_s3')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: http://fake_s3
[2024-05-24T11:49:50.090+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_from_github_to_s3, task_id=download_and_upload_to_s3, run_id=scheduled__2023-03-13T00:00:00+00:00, execution_date=20230313T000000, start_date=20240524T114949, end_date=20240524T114950
[2024-05-24T11:49:50.096+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task download_and_upload_to_s3 (Invalid endpoint: http://fake_s3; 73)
[2024-05-24T11:49:50.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T11:49:50.125+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T11:49:50.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-24T12:00:00.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T12:00:00.904+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2024-05-24T12:00:00.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [queued]>
[2024-05-24T12:00:00.908+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-24T12:00:00.916+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_to_s3> on 2023-03-13 00:00:00+00:00
[2024-05-24T12:00:00.919+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=245) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T12:00:00.920+0000] {standard_task_runner.py:63} INFO - Started process 250 to run task
[2024-05-24T12:00:00.920+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_from_github_to_s3', 'download_and_upload_to_s3', 'scheduled__2023-03-13T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/upload_from_github_to_s3_dag.py', '--cfg-path', '/tmp/tmpxaod7d06']
[2024-05-24T12:00:00.921+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask download_and_upload_to_s3
[2024-05-24T12:00:00.945+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-13T00:00:00+00:00 [running]> on host b2ab95bd73fd
[2024-05-24T12:00:00.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_from_github_to_s3' AIRFLOW_CTX_TASK_ID='download_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-13T00:00:00+00:00'
[2024-05-24T12:00:00.989+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T12:00:01.232+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-24T12:00:01.299+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T12:00:01.300+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T12:00:01.305+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_from_github_to_s3, task_id=download_and_upload_to_s3, run_id=scheduled__2023-03-13T00:00:00+00:00, execution_date=20230313T000000, start_date=20240524T120000, end_date=20240524T120001
[2024-05-24T12:00:01.347+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T12:00:01.355+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
