[2024-05-24T11:54:53.829+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T11:54:53.839+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2024-05-24T11:54:53.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2024-05-24T11:54:53.843+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-24T11:54:53.848+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_to_s3> on 2023-03-23 00:00:00+00:00
[2024-05-24T11:54:53.850+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=127) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T11:54:53.851+0000] {standard_task_runner.py:63} INFO - Started process 134 to run task
[2024-05-24T11:54:53.851+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_from_github_to_s3', 'download_and_upload_to_s3', 'scheduled__2023-03-23T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/upload_from_github_to_s3_dag.py', '--cfg-path', '/tmp/tmp0a7ir53n']
[2024-05-24T11:54:53.852+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask download_and_upload_to_s3
[2024-05-24T11:54:53.873+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [running]> on host b2ab95bd73fd
[2024-05-24T11:54:53.906+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_from_github_to_s3' AIRFLOW_CTX_TASK_ID='download_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-23T00:00:00+00:00'
[2024-05-24T11:54:53.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T11:54:54.420+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-24T11:54:54.467+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T11:54:54.468+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/upload_from_github_to_s3_dag.py", line 33, in download_and_upload_to_s3
    s3 = boto3.client('s3', endpoint_url='http://fake_s3:4569')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: http://fake_s3:4569
[2024-05-24T11:54:54.473+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_from_github_to_s3, task_id=download_and_upload_to_s3, run_id=scheduled__2023-03-23T00:00:00+00:00, execution_date=20230323T000000, start_date=20240524T115453, end_date=20240524T115454
[2024-05-24T11:54:54.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 183 for task download_and_upload_to_s3 (Invalid endpoint: http://fake_s3:4569; 134)
[2024-05-24T11:54:54.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T11:54:54.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-24T12:00:01.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T12:00:01.574+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2024-05-24T12:00:01.578+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [queued]>
[2024-05-24T12:00:01.578+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-24T12:00:01.584+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_upload_to_s3> on 2023-03-23 00:00:00+00:00
[2024-05-24T12:00:01.587+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-24T12:00:01.588+0000] {standard_task_runner.py:63} INFO - Started process 266 to run task
[2024-05-24T12:00:01.588+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_from_github_to_s3', 'download_and_upload_to_s3', 'scheduled__2023-03-23T00:00:00+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/upload_from_github_to_s3_dag.py', '--cfg-path', '/tmp/tmp5ccv0uye']
[2024-05-24T12:00:01.588+0000] {standard_task_runner.py:91} INFO - Job 280: Subtask download_and_upload_to_s3
[2024-05-24T12:00:01.608+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_from_github_to_s3.download_and_upload_to_s3 scheduled__2023-03-23T00:00:00+00:00 [running]> on host b2ab95bd73fd
[2024-05-24T12:00:01.643+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_from_github_to_s3' AIRFLOW_CTX_TASK_ID='download_and_upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-03-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-23T00:00:00+00:00'
[2024-05-24T12:00:01.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T12:00:01.960+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-05-24T12:00:02.019+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-24T12:00:02.020+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T12:00:02.024+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_from_github_to_s3, task_id=download_and_upload_to_s3, run_id=scheduled__2023-03-23T00:00:00+00:00, execution_date=20230323T000000, start_date=20240524T120001, end_date=20240524T120002
[2024-05-24T12:00:02.061+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T12:00:02.068+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T12:00:02.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
